# Generated by Django 5.1.1 on 2024-09-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_number', models.IntegerField()),
                ('without_jacket', models.BooleanField(default=False)),
                ('without_helmet', models.BooleanField(default=False)),
                ('both', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploaded_images/images/')),
            ],
        ),
    ]
