# Generated by Django 5.1.1 on 2024-09-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violation',
            options={'ordering': ['camera_number'], 'verbose_name': 'Violation', 'verbose_name_plural': 'Violations'},
        ),
        migrations.AlterField(
            model_name='violation',
            name='camera_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='violation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images/images'),
        ),
    ]
