# Generated by Django 5.1.1 on 2024-10-08 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation', '0002_alter_violation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(choices=[('Without Shoes', 'Without Shoes'), ('Without Helmet', 'Without Helmet'), ('Both', 'Both')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='violation',
            name='camera_number',
            field=models.IntegerField(),
        ),
    ]
